### PR TITLE
fix misleading note

### PR DESCRIPTION
**Pull request by PranavPurwar**

### CODE REVIEW

**Comment by j-px** [comment]
cool nitpicking

**Comment by PranavPurwar** [comment]
Iyxan asked TheClashFruit to do it in server, but he didn't saw it so i added it nyself.

**Comment by iyxan23** [comment]
"abandoned" is too strong of a word and does not describe exactly why. I'm going to do this myself :trollface:

**Comment by PranavPurwar** [comment]
Whatever, It would still not start in future anyways :trollface:

**Comment by iyxan23** [comment]
bet :trollface:

**Pull request closed without merging**
